language: r
script:
  - R CMD build . --no-manual --no-build-vignettes
  - R CMD check *tar.gz --no-manual --no-build-vignettes --ignore-vignettes --no-examples
repos:
  CRAN: https://cloud.r-project.org
  BioCsoft: https://bioconductor.org/packages/devel/bioc
  BioCann: https://bioconductor.org/packages/devel/data/annotation
  BioCexp: https://bioconductor.org/packages/devel/data/experiment
install:
  - R -e 'install.packages(c("ComplexHeatmap","matrixStats","GetoptLong","circlize","GlobalOptions","clue","RColorBrewer","cluster","skmeans","png","mclust","crayon","xml2","microbenchmark","httr","knitr","markdown","digest","impute","brew","Rcpp","BiocGenerics","eulerr"))'
env:
    - _R_CHECK_FORCE_SUGGESTS_=false
